# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6e0f8b9d08c16e5051eabfdb8927ac2cdaf54e8856e0656a7d022bb5292584333683e42fb08a096eff0118558ee17d1e4ab1844cc4b3ceeb19992f4d2dbcf8a

test:
  secret_key_base: f8cf37cfcc1684389586c240e9d4297e26041b471cb5be1b4c4c19a475dbb5c183c32c6a0fd4535c933da456f9080e8a97aa101572b8782e02606bfc052dae05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
